---
# This Playbook deploys redis from github source

- hosts: redis-from-src
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  tasks:
  - include: tasks/main.yml
