---
# This Playbook deploys redis from github source

- hosts: redis-from-src
  vars_files:
    - vars/main.yml
  user: root
  #sudo: True
  tasks:
  - include: tasks/install-dependencies.yml
  - include: tasks/install-redis.yml
