---

- name: Install redis dependencies 
  action: apt pkg=$item state=installed update_cache=yes
  with_items:
    - build-essential 

## Make sure right version of python will be used
#- name: ensure /usr/local/bin/python2 links to /usr/bin/python
#  file: state=link src=/usr/bin/python path=/usr/local/bin/python2
#
## Install correct version of ruby from source
#- name: ensure directory /tmp/ruby is present
#  file: state=directory path=/tmp/ruby
#
#- name: ensure ruby is downloaded
#  get_url: url=$rubyUrl dest=/tmp/ruby
#
#- name: ensure ruby is extracted
#  command: tar -xf ruby-1.9.3-p327.tar.gz chdir=/tmp/ruby creates=$tmpRubyPath
#
#- name: ensure ruby is configured
#  command: ./configure chdir=$tmpRubyPath creates=$tmpRubyPath/Makefile
#
#- name: ensure ruby is compiled
#  command: make chdir=$tmpRubyPath creates=$tmpRubyPath/ruby
#
#- name: ensure ruby is installed
#  command: make install chdir=$tmpRubyPath creates=/usr/local/bin/ruby
#
## Install bundler
#- name: ensure bundler is installed
#  gem: name=bundler state=present 
## command: gem install bundler creates=/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.3.0
#
## Add git user
#- name: ensure user git is present
#  # Possible problem is that --disabled-password is not set explicitly – I couldn’t find anything like that.
#  user: state=present name=git system=yes shell=/bin/sh comment="Git Version Control" 
#
## Clone gitlab shell
#- name: Get gitlab-shell source
#  # Not sure if this is checking out the right version. And why 
# #git checkout v1.1.0
# #git checkout -b v1.1.0
#  git: repo=https://github.com/gitlabhq/gitlab-shell.git dest=/home/git/gitlab-shell version=v1.1.0
#
#- name: Set git as owner
#  file: path=/home/git/gitlab-shell owner=git group=git recurse=yes state=directory
#
#- name: Set the /home/git/gitlab-shell/config.yml
#  action: template src=templates/home/git/gitlab-shell/config.yml.j2 dest=/home/git/gitlab-shell/config.yml
#
## Do setup
#- name: Install gitlab-shell
#  command: sudo -u git -H ./bin/install chdir=/home/git/gitlab-shell creates=/home/git/repositories
#
##Install also touches this file, multiple creates=?
### File used as authorized_keys for gitlab user
##auth_file: "/home/git/.ssh/authorized_keys"
