---

- name: redis-from-src | Install redis dependencies 
  action: apt pkg=$item state=installed update_cache=$global_update_apt_cache
  with_items:
    - build-essential 

- name: redis-from-src | Clone redis source
  git: repo=$redis_from_src_repository dest=$redis_from_src_src_dir version=$redis_from_src_version

- name: redis-from-src | Make redis 
  command: make chdir=$redis_from_src_src_dir

- name: redis-from-src | Make install
  command: make install chdir=$redis_from_src_src_dir

- name: redis-from-src | Make /var/redis directory 
  file: state=directory path=/etc/redis owner=root group=root

- name: redis-from-src | Make /var/redis/$redis_from_src_port dir
  file: state=directory path=/var/redis/$redis_from_src_port owner=root group=root

- name: redis-from-src | Copy over redis init script 
  template: src=templates/etc/init.d/redis_PORT.j2 dest=/etc/init.d/redis_$redis_from_src_port owner=root group=root mode=0755

- name: redis-from-src | Copy over redis config
  template: src=templates/etc/redis/PORT.conf.j2 dest=/etc/redis/$redis_from_src_port.conf owner=root group=root

- name: redis-from-src | Start redis on boot 
  command: update-rc.d redis_$redis_from_src_port defaults 21

- name: redis-from-src | Restart redis 
  service: name=redis_$redis_from_src_port state=started
